import {
  addClip,
  clearUndo,
  deleteClip,
  duplicateClip,
  getClipsForProject,
  getProject,
  getSettings,
  getUndoSnapshot,
  listProjects,
  moveClip,
  setLastOpenedProjectId,
  undoDeleteLastClip,
  updateClipTrim,
} from './storage'
import { ensureClipThumbs } from './thumbs'
import {
  effectiveDurationMs,
  type ClipId,
  type ClipRecord,
  type Project,
  type ProjectId,
} from './types'

export interface ProjectSummary extends Project {
  clipCount: number
  durationMs: number
  /** First available clip thumbnail, for the project slot background. */
  posterThumb: Blob | null
}

export interface ProjectLoaderData {
  project: Project | null
  clips: ClipRecord[]
  canUndo: boolean
  onboardingDismissed: boolean
  error: string | null
}

export async function loadHomeProjects(): Promise<ProjectSummary[]> {
  const list = await listProjects()
  // Stable slot order (creation order) — OK Video-style fixed project slots
  // that don't shuffle every time you open a project.
  list.sort((a, b) => a.createdAt - b.createdAt)
  return Promise.all(
    list.map(async (project) => {
      const clips = await getClipsForProject(project.id)
      const durationMs = clips.reduce((sum, clip) => sum + effectiveDurationMs(clip), 0)
      const withThumb = clips.find((clip) => clip.thumbs && clip.thumbs.length > 0)
      return {
        ...project,
        clipCount: clips.length,
        durationMs,
        posterThumb: withThumb?.thumbs?.[0] ?? null,
      }
    }),
  )
}

export async function loadProjectPage(projectId: ProjectId): Promise<ProjectLoaderData> {
  try {
    const [project, clips, undo, settings] = await Promise.all([
      getProject(projectId),
      getClipsForProject(projectId),
      getUndoSnapshot(projectId),
      getSettings(),
    ])
    if (!project) {
      return {
        project: null,
        clips: [],
        canUndo: false,
        onboardingDismissed: settings.onboardingDismissed,
        error: 'Project not found',
      }
    }
    await setLastOpenedProjectId(projectId)
    // Backfill filmstrip thumbnails for clips recorded before they existed.
    const hydrated = await Promise.all(clips.map((clip) => ensureClipThumbs(clip)))
    return {
      project,
      clips: hydrated,
      canUndo: !!undo,
      onboardingDismissed: settings.onboardingDismissed,
      error: null,
    }
  } catch (err) {
    return {
      project: null,
      clips: [],
      canUndo: false,
      onboardingDismissed: true,
      error: err instanceof Error ? err.message : 'Failed to load project',
    }
  }
}

export async function appendRecording(
  projectId: ProjectId,
  input: { blob: Blob; mimeType: string; durationMs: number; width?: number; height?: number },
): Promise<ClipRecord> {
  const clip = await addClip({
    projectId,
    blob: input.blob,
    mimeType: input.mimeType,
    durationMs: input.durationMs,
    width: input.width,
    height: input.height,
  })
  await clearUndo(projectId)
  // Thumbnails are generated by the loader backfill on the next revalidation.
  return clip
}

export async function removeClip(clipId: ClipId): Promise<void> {
  await deleteClip(clipId)
}

export async function undoLastDelete(projectId: ProjectId): Promise<ClipRecord | null> {
  return undoDeleteLastClip(projectId)
}

export async function duplicateSelectedClip(clipId: ClipId): Promise<ClipRecord> {
  return duplicateClip(clipId)
}

export async function moveSelectedClip(
  projectId: ProjectId,
  clipId: ClipId,
  direction: 'left' | 'right',
): Promise<void> {
  await moveClip(projectId, clipId, direction)
}

export async function trimClip(
  clipId: ClipId,
  trimStartMs: number,
  trimEndMs: number,
): Promise<void> {
  await updateClipTrim(clipId, trimStartMs, trimEndMs)
}
