import {
  addClip,
  clearUndo,
  deleteClip,
  duplicateClip,
  getClipsForProject,
  getProject,
  getSettings,
  getUndoSnapshot,
  listProjects,
  moveClip,
  setLastOpenedProjectId,
  undoDeleteLastClip,
  updateClipTrim,
} from './storage'
import { estimateStorageSpace, type StorageSpace } from './storage-space'
import { ensureClipThumbs } from './thumbs'
import {
  effectiveDurationMs,
  type ClipId,
  type ClipRecord,
  type Project,
  type ProjectId,
} from './types'

export interface ProjectSummary extends Project {
  clipCount: number
  durationMs: number
  /** First available clip thumbnail, for the project slot background. */
  posterThumb: Blob | null
}

export interface ProjectLoaderData {
  project: Project | null
  clips: ClipRecord[]
  canUndo: boolean
  onboardingDismissed: boolean
  /** True when the one-time "Remove Watermark" purchase is unlocked. */
  watermarkRemoved: boolean
  /** Device storage estimate (null when the API is unavailable). */
  storage: StorageSpace | null
  /** Opt-in: tag new clips with device location. */
  locationTaggingEnabled: boolean
  error: string | null
}

export interface HomeLoaderData {
  projects: ProjectSummary[]
  storage: StorageSpace | null
}

export async function loadHomePage(): Promise<HomeLoaderData> {
  const [projects, storage] = await Promise.all([loadHomeProjects(), estimateStorageSpace()])
  return { projects, storage }
}

export async function loadHomeProjects(): Promise<ProjectSummary[]> {
  const list = await listProjects()
  // Stable slot order (creation order) — OK Video-style fixed project slots
  // that don't shuffle every time you open a project.
  list.sort((a, b) => a.createdAt - b.createdAt)
  return Promise.all(
    list.map(async (project) => {
      const clips = await getClipsForProject(project.id)
      const durationMs = clips.reduce((sum, clip) => sum + effectiveDurationMs(clip), 0)
      // Prefer any clip with a high-res poster over an older thumbs-only one.
      const withPoster = clips.find((clip) => clip.poster)
      const withThumb = clips.find((clip) => clip.thumbs && clip.thumbs.length > 0)
      return {
        ...project,
        clipCount: clips.length,
        durationMs,
        posterThumb: withPoster?.poster ?? withThumb?.thumbs?.[0] ?? null,
      }
    }),
  )
}

export async function loadProjectPage(projectId: ProjectId): Promise<ProjectLoaderData> {
  try {
    const [project, clips, undo, settings, storage] = await Promise.all([
      getProject(projectId),
      getClipsForProject(projectId),
      getUndoSnapshot(projectId),
      getSettings(),
      estimateStorageSpace(),
    ])
    if (!project) {
      return {
        project: null,
        clips: [],
        canUndo: false,
        onboardingDismissed: settings.onboardingDismissed,
        watermarkRemoved: settings.watermarkRemoved === true,
        storage,
        locationTaggingEnabled: settings.locationTaggingEnabled === true,
        error: 'Project not found',
      }
    }
    await setLastOpenedProjectId(projectId)
    // Backfill filmstrip thumbnails for clips that lack them. Serially —
    // Android caps concurrent video decoders hard, and this normally touches
    // at most the clip that was just recorded.
    const hydrated: ClipRecord[] = []
    for (const clip of clips) {
      hydrated.push(await ensureClipThumbs(clip))
    }
    return {
      project,
      clips: hydrated,
      canUndo: !!undo,
      onboardingDismissed: settings.onboardingDismissed,
      watermarkRemoved: settings.watermarkRemoved === true,
      storage,
      locationTaggingEnabled: settings.locationTaggingEnabled === true,
      error: null,
    }
  } catch (err) {
    return {
      project: null,
      clips: [],
      canUndo: false,
      onboardingDismissed: true,
      watermarkRemoved: false,
      storage: null,
      locationTaggingEnabled: false,
      error: err instanceof Error ? err.message : 'Failed to load project',
    }
  }
}

export async function appendRecording(
  projectId: ProjectId,
  input: {
    blob: Blob
    mimeType: string
    durationMs: number
    width?: number
    height?: number
    lat?: number
    lng?: number
    locationAccuracyM?: number
  },
): Promise<ClipRecord> {
  const clip = await addClip({
    projectId,
    blob: input.blob,
    mimeType: input.mimeType,
    durationMs: input.durationMs,
    width: input.width,
    height: input.height,
    lat: input.lat,
    lng: input.lng,
    locationAccuracyM: input.locationAccuracyM,
  })
  await clearUndo(projectId)
  // Thumbnails are generated by the loader backfill on the next revalidation.
  return clip
}

export async function removeClip(clipId: ClipId): Promise<void> {
  await deleteClip(clipId)
}

export async function undoLastDelete(projectId: ProjectId): Promise<ClipRecord | null> {
  return undoDeleteLastClip(projectId)
}

export async function duplicateSelectedClip(clipId: ClipId): Promise<ClipRecord> {
  return duplicateClip(clipId)
}

export async function moveSelectedClip(
  projectId: ProjectId,
  clipId: ClipId,
  direction: 'left' | 'right',
): Promise<void> {
  await moveClip(projectId, clipId, direction)
}

export async function trimClip(
  clipId: ClipId,
  trimStartMs: number,
  trimEndMs: number,
): Promise<void> {
  await updateClipTrim(clipId, trimStartMs, trimEndMs)
}
